title = "Matías Moreno"
baseURL = "https://matiasmoreno.github.io/portfolio/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    title = "Matías Moreno"
    weight = 1
    contentDir = "content/en"
  [languages.es]
    title = "Matías Moreno"
    weight = 2
    contentDir = "content/es"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/matiasmoreno"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/morenomatias/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = ""
  recent_posts_number = 2